from PyQt5 import QtCore, QtGui, QtWidgets
from ui.photo_box import PhotoBox
from PyQt5.QtGui import QIcon, QColor
from PyQt5.QtCore import QSize

class Ui_Describer(object):
    def setupUi(self, Describer):
        Describer.setObjectName("Describer")
        Describer.resize(900, 615)        
        
        self.centralwidget = QtWidgets.QWidget(Describer)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_add_describe = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_add_describe.setMinimumSize(QtCore.QSize(0, 31))
        self.lineEdit_add_describe.setText("")
        self.lineEdit_add_describe.setObjectName("lineEdit_add_describe")
        self.horizontalLayout_3.addWidget(self.lineEdit_add_describe)
        self.comboBox_ai = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ai.setMinimumSize(QtCore.QSize(150, 31))
        self.comboBox_ai.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_ai.setObjectName("comboBox_ai")
        self.comboBox_ai.addItem("")
        self.comboBox_ai.addItem("")
        self.comboBox_ai.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_ai)
        self.btn_add_to_text = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_to_text.setMinimumSize(QtCore.QSize(120, 31))
        self.btn_add_to_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_add_to_text.setObjectName("btn_add_to_text")
        self.horizontalLayout_3.addWidget(self.btn_add_to_text)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_ai_describe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ai_describe.setMinimumSize(QtCore.QSize(200, 31))
        self.btn_ai_describe.setMaximumSize(QtCore.QSize(16777215, 31))
        self.btn_ai_describe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_ai_describe.setObjectName("btn_ai_describe")
        self.horizontalLayout_7.addWidget(self.btn_ai_describe)
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setMinimumSize(QtCore.QSize(100, 31))
        self.comboBox.setMaximumSize(QtCore.QSize(100, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox)
        self.comboBox_begin = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_begin.setMinimumSize(QtCore.QSize(60, 31))
        self.comboBox_begin.setMaximumSize(QtCore.QSize(60, 31))
        self.comboBox_begin.setObjectName("comboBox_begin")
        self.comboBox_begin.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_begin)
        self.comboBox_end = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_end.setMinimumSize(QtCore.QSize(60, 31))
        self.comboBox_end.setMaximumSize(QtCore.QSize(60, 31))
        self.comboBox_end.setObjectName("comboBox_end")
        self.comboBox_end.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_end)
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setMinimumSize(QtCore.QSize(120, 31))
        self.btn_stop.setMaximumSize(QtCore.QSize(120, 16777215))
        self.btn_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout_7.addWidget(self.btn_stop)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.comboBox_number = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_number.setMinimumSize(QtCore.QSize(60, 31))
        self.comboBox_number.setMaximumSize(QtCore.QSize(16777215, 31))
        self.comboBox_number.setObjectName("comboBox_number")
        
        self.horizontalLayout_4.addWidget(self.comboBox_number)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        
        self.label_count = QtWidgets.QLabel(self.centralwidget)
        self.label_count.setObjectName("label_count")
        self.horizontalLayout_4.addWidget(self.label_count)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        
        self.checkBox_copypaste = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_copypaste.setObjectName("checkBox_copypaste")
        self.horizontalLayout_4.addWidget(self.checkBox_copypaste)
        
        self.btn_clear_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clear_all.setMinimumSize(QtCore.QSize(120, 31))
        self.btn_clear_all.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clear_all.setObjectName("btn_clear_all")
        self.horizontalLayout_4.addWidget(self.btn_clear_all)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 408))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        
        self.verticalLayout_photos = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_photos.setObjectName("verticalLayout_photos")
        
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_info = QtWidgets.QLabel(self.centralwidget)
        self.label_info.setMinimumSize(QtCore.QSize(0, 31))
        self.label_info.setObjectName("label_info")
        self.horizontalLayout_5.addWidget(self.label_info)
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setMinimumSize(QtCore.QSize(200, 31))
        self.progressBar.setMaximumSize(QtCore.QSize(200, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_5.addWidget(self.progressBar)
    
        
        
        self.pushButton_settings = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_settings.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_settings.setMaximumSize(QtCore.QSize(31, 31))
        icon = QIcon("img/settings.png")  # Путь к вашему PNG-файлу
        self.pushButton_settings.setIconSize(QSize(17, 17))
        self.pushButton_settings.setIcon(icon)
        
        self.pushButton_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_settings.setObjectName("pushButton_settings")
        self.horizontalLayout_5.addWidget(self.pushButton_settings)
        
        self.pushButton_author = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_author.setMinimumSize(QtCore.QSize(31, 31))
        self.pushButton_author.setMaximumSize(QtCore.QSize(31, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_author.setFont(font)
        self.pushButton_author.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_author.setObjectName("pushButton_author")
        self.horizontalLayout_5.addWidget(self.pushButton_author)
        
        
        
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        Describer.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(Describer)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menuBar.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menuFile.setObjectName("menuFile")
        Describer.setMenuBar(self.menuBar)
        self.action_openFolder = QtWidgets.QAction(Describer)
        self.action_openFolder.setShortcutVisibleInContextMenu(True)
        self.action_openFolder.setObjectName("action_openFolder")
        self.action_openPictures = QtWidgets.QAction(Describer)
        self.action_openPictures.setShortcutVisibleInContextMenu(True)
        self.action_openPictures.setObjectName("action_openPictures")
        self.action_loadList = QtWidgets.QAction(Describer)
        self.action_loadList.setShortcutVisibleInContextMenu(True)
        self.action_loadList.setObjectName("action_loadList")
        
        self.action_addPhotos = QtWidgets.QAction(Describer)
        self.action_addPhotos.setShortcutVisibleInContextMenu(True)
        self.action_addPhotos.setObjectName("action_addPhotos")
        
        
        self.action_saveList = QtWidgets.QAction(Describer)
        self.action_saveList.setShortcutVisibleInContextMenu(True)
        self.action_saveList.setObjectName("action_saveList")
        self.action_excel = QtWidgets.QAction(Describer)
        self.action_excel.setShortcutVisibleInContextMenu(True)
        self.action_excel.setObjectName("action_excel")
        
        self.action_clearAll = QtWidgets.QAction(Describer)
        self.action_clearAll.setShortcutVisibleInContextMenu(True)
        self.action_clearAll.setObjectName("action_action_clearAll")
        
        
        
        self.menuFile.addAction(self.action_openFolder)
        self.menuFile.addAction(self.action_openPictures)
        self.menuFile.addAction(self.action_loadList)
        self.menuFile.addAction(self.action_addPhotos)
        self.menuFile.addAction(self.action_saveList)
        self.menuFile.addAction(self.action_excel)
        self.menuFile.addAction(self.action_clearAll)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.retranslateUi(Describer)
        QtCore.QMetaObject.connectSlotsByName(Describer)

    def retranslateUi(self, Describer):
        _translate = QtCore.QCoreApplication.translate
        Describer.setWindowTitle(_translate("Describer", "Describer 1.0"))
        self.lineEdit_add_describe.setPlaceholderText(_translate("Describer", "Добавить к описанию для всех картинок"))
        self.comboBox_ai.setItemText(0, _translate("Describer", "Добавить в конец"))
        self.comboBox_ai.setItemText(1, _translate("Describer", "Добавить в начало"))
        self.comboBox_ai.setItemText(2, _translate("Describer", "Заменить"))
        
        self.btn_add_to_text.setText(_translate("Describer", "Добавить"))
        self.btn_ai_describe.setText(_translate("Describer", "AI описание списка"))
        self.btn_ai_describe.setShortcut(_translate("Describer", "Ctrl+A"))
        self.comboBox.setItemText(0, _translate("Describer", "Все"))
        self.comboBox.setItemText(1, _translate("Describer", "Выбрать"))
        self.comboBox_begin.setItemText(0, _translate("Describer", "1"))
        self.comboBox_end.setItemText(0, _translate("Describer", "31"))
        self.btn_stop.setText(_translate("Describer", "Остановить"))
        self.btn_stop.setShortcut(_translate("Describer", "Ctrl+X"))
        self.label_2.setText(_translate("Describer", "Текущий номер для автокопирования:"))
        
        self.label.setText(_translate("Describer", "F12 - Автокопирование со сдвигом"))
        self.btn_clear_all.setText(_translate("Describer", "Очистить всё"))
        self.btn_clear_all.setShortcut(_translate("Describer", "Ctrl+Q"))
        
        self.pushButton_author.setText(_translate("Describer", "?"))
        self.menuFile.setTitle(_translate("Describer", "Файл"))
        self.action_openFolder.setText(_translate("Describer", "Выбрать папку"))
        self.action_openFolder.setShortcut(_translate("Describer", "Ctrl+O"))
        self.action_openPictures.setText(_translate("Describer", "Выбрать картинки"))
        self.action_openPictures.setShortcut(_translate("Describer", "Ctrl+I"))
        self.action_loadList.setText(_translate("Describer", "Загрузить список"))
        self.action_loadList.setShortcut(_translate("Describer", "Ctrl+L"))
        
        self.action_addPhotos.setText(_translate("Describer", "Добавить фотографии"))
        self.action_addPhotos.setShortcut(_translate("Describer", "Ctrl+A"))
        self.checkBox_copypaste.setText(_translate("Describer", "+ Вставка"))
        
        self.action_saveList.setText(_translate("Describer", "Сохранить список"))
        self.action_saveList.setShortcut(_translate("Describer", "Ctrl+U"))
        self.action_excel.setText(_translate("Describer", "Экспорт в Excel"))
        self.action_excel.setShortcut(_translate("Describer", "Ctrl+E"))
        self.action_clearAll.setText(_translate("Describer", "Очистить список"))
        self.action_clearAll.setShortcut(_translate("Describer", "Ctrl+Q"))
